[platformio]
src_dir = main

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf

monitor_speed = 115200

; This tells PlatformIO where your 10 satellite subsystems are
lib_extra_dirs = components

; This helps the compiler find the headers across different folders
build_flags = 
    -I main
    -I components/adcs
    -I components/archive
    -I components/cdh
    -I components/comms
    -I components/eps
    -I components/fdir
    -I components/sat_hal
    -I components/hk
    -I components/payload
    -I components/time